
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE OR REPLACE  VIEW `ws_syspat_action_activ` AS 
select * from `ACTION_ACTIV`;

--
-- Structure de la vue `ws_syspat_action_activ_has_indic_pefa`
--

CREATE OR REPLACE VIEW `ws_syspat_action_activ_has_indic_pefa` AS 
select * from `ACTION_ACTIV_HAS_INDIC_PEFA`;

-- --------------------------------------------------------

--
-- Structure de la vue `ws_syspat_act_periods`
--

CREATE OR REPLACE  VIEW `ws_syspat_act_periods` AS 
select * from `ACT_PERIODS`;

-- --------------------------------------------------------

--
-- Structure de la vue `ws_syspat_eval_action_activ`
--

CREATE  OR REPLACE VIEW `ws_syspat_eval_action_activ` AS 
select * from `EVAL_ACTION_ACTIV`;

-- --------------------------------------------------------

--
-- Structure de la vue `ws_syspat_eval_act_indic_pefa`
--

CREATE OR REPLACE VIEW `ws_syspat_eval_act_indic_pefa` AS 
select * from `EVAL_ACT_INDIC_PEFA`;

-- --------------------------------------------------------

--
-- Structure de la vue `ws_syspat_indicator_pefa`
--

CREATE OR REPLACE VIEW `ws_syspat_indicator_pefa` AS 
select * from `INDICATOR_PEFA`;


Create or replace view ws_syspat_actions as
SELECT DISTINCT (ACTION_ACTIV.ACTION_ACTIV_REF)as ACTION_ACTIV_REF, 
			ACTION_ACTIV.DESCRIPTION as DESCRIPTION, DATE_FORMAT(ACT_PERIODS.START_DATE, '%d/%m/%Y')as START_DATE, DATE_FORMAT(ACT_PERIODS.DUE_DATE, '%d/%m/%Y') as DUE_DATE,
			STRUCTURE.STRUCTURE_CODE, RESPONSIBLE.NAME as RESPONSIBLE_NAME, ACTION_ACTIV.DOMAIN_CODE, ACTION_ACTIV.DIMENSION_CODE 
FROM ACTION_ACTIV  LEFT OUTER JOIN STRC_HAS_DOMN_HAS_RESP on ACTION_ACTIV.ID_STRC_HAS_DOMN_HAS_RESP = STRC_HAS_DOMN_HAS_RESP.ID_STRC_HAS_DOMN_HAS_RESP  LEFT OUTER JOIN RESPONSIBLE on STRC_HAS_DOMN_HAS_RESP.ID_RESPONSIBLE = RESPONSIBLE.ID_RESPONSIBLE INNER JOIN STRUCTURE on STRC_HAS_DOMN_HAS_RESP.ID_STRUCTURE = STRUCTURE.ID_STRUCTURE  LEFT OUTER JOIN ACT_PERIODS on ACTION_ACTIV.ACTION_ACTIV_REF = ACT_PERIODS.ACTION_ACTIV_REF  LEFT OUTER JOIN DOMAIN_GOAL ON DOMAIN_GOAL.DOMAIN_CODE = ACTION_ACTIV.DOMAIN_CODE  LEFT OUTER JOIN DOMAIN_RESULT ON DOMAIN_RESULT.DOMAIN_CODE = ACTION_ACTIV.DOMAIN_CODE   LEFT OUTER JOIN ACTION_ACTIV_HAS_INDIC_PEFA ON 	ACTION_ACTIV_HAS_INDIC_PEFA.ACTION_ACTIV_REF = ACTION_ACTIV.ACTION_ACTIV_REF  LEFT OUTER JOIN ACT_RESOURCE ON ACT_RESOURCE.ACTION_ACTIV_REF = ACTION_ACTIV.ACTION_ACTIV_REF; 

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
